/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.2/userguide/building_java_projects.html
 */
version = "0.1.0"

plugins {
    id("org.springframework.boot") version "3.2.6"
    application
    java
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.1")
    testImplementation("org.springframework.boot:spring-boot-starter-test:3.2.6")
    implementation("com.google.guava:guava:30.1.1-jre")
    implementation("org.springframework.boot:spring-boot-starter-webflux:3.2.6")
    implementation("org.springframework.boot:spring-boot-starter:3.2.6")
}

application {
    // Define the main class for the application.
    mainClass.set("proxy.ProxyServiceApplication")
}

java {
    withSourcesJar()
}

tasks.test {
    useJUnitPlatform()
}

tasks.jar {
    manifest {
        attributes(mapOf("Implementation-Title" to project.name,
            "Implementation-Version" to project.version,
            "Main-Class" to "proxy.ProxyServiceApplication"))
    }
}
