@startuml

!include <C4/C4_Container>

Person(client, "Client", "Пользователь системы")
System_Boundary(platform, "Cinema abyss") {
    Container(clientFrontend, "Client web interface", "Client frontend")
    Container(clientMobile, "Mobile client", "mobile app")
    Container(clientTv, "Smart TV client", "Smart TV app")
    Container(apiGateway, "API Gateway", "API Gateway")
    Container(userManagement, "User Management Service", "Сервис управления пользователями")
    ContainerDb(userDb, "User Database", "PostgreSQL", "БД пользователей")
    Container(paymentService, "Payment Service", "Сервис оплаты")
    ContainerDb(paymentDb, "Payment Database", "PostgreSQL", "БД платежей")
    Container(subscriptionService, "Subscription Service", "Сервис подписок")
    ContainerDb(subscriptionDb, "Subscription Database", "PostgreSQL", "БД подписок")
    Container(eventsService, "Events Service", "Сервис событий и уведомлений")
    ContainerQueue(messageQueue, "Message Queue", "Kafka + Zookeeper", "Брокер и очередь сообщений для асинхронной коммуникации между сервисами")
    Container(moviesService, "Movie Service", "Сервис управления фильмами и сериалами")
    ContainerDb(movieDb, "Movie Database", "PostgreSQL", "БД фильмов и сериалов")



    Container(prometheus, "Prometheus", "Система мониторинга и оповещений + Prometheus TSDB", "Сбор и хранение метрик")
    Container(grafana, "Grafana", "Платформа аналитики и визуализации", "Визуализация метрик и создание дашбордов")
}
Container_Ext(payment, "Payment GateWay", "API (External)", "Обработка запросов для операций оплаты")

Rel(client, clientFrontend, "Просмотр и управление")
Rel(client, clientMobile, "Просмотр и управление")
Rel(client, clientTv, "Просмотр и управление")
Rel(clientFrontend, apiGateway, "client requests", "HTTP/gRPC")
Rel(clientMobile, apiGateway, "client requests", "HTTP/gRPC")
Rel(clientTv, apiGateway, "client requests", "HTTP/gRPC")
Rel(userManagement, userDb, "Чтение и запись данных пользователей", "JDBC")
Rel(subscriptionService, subscriptionDb, "Чтение и запись данных о подписках", "JDBC")
Rel(eventsService, messageQueue, "Публикация событий", "Kafka")
Rel(moviesService, movieDb, "Чтение и запись данных о фильмах и сериалах", "JDBC")

Rel(messageQueue, moviesService, "Отправка событий", "Kafka")
Rel(messageQueue, userManagement, "Отправка событий", "Kafka")
Rel(messageQueue, paymentService, "Отправка событий", "Kafka")


Rel_R(apiGateway, paymentService, "Оплата", "HTTP")
Rel_R(apiGateway, "eventsService", "Асинхронная обработка событий", "HTTP/gRPC")
Rel_L(apiGateway, userManagement, "Управление и информация о пользователях" ,"HTTP")
Rel(apiGateway, subscriptionService, "Управление подписками", "HTTP")
Rel(apiGateway, moviesService, "Управление фильмами и сериалами", "HTTP")
Rel(apiGateway, prometheus, "Сбор метрик", "HTTP")
Rel(grafana, prometheus, "Запрос метрик для визуализации", "HTTP")

Rel_R(paymentService, payment, "Инициирует оплату через API", "HTTP")
Rel(paymentService, paymentDb, "Чтение и запись данных о платежах", "JDBC")




@enduml